# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/p7810456/FPGADesign/Simple_MemmapPeriph/Simple_MemmapPeriph.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_xbar_0/TopLevelDesign_xbar_0.xci
# IP: The module: 'TopLevelDesign_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/p7810456/FPGADesign/Simple_MemmapPeriph/Simple_MemmapPeriph.gen/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_xbar_0/TopLevelDesign_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevelDesign_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/p7810456/FPGADesign/Simple_MemmapPeriph/Simple_MemmapPeriph.srcs/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_xbar_0/TopLevelDesign_xbar_0.xci
# IP: The module: 'TopLevelDesign_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/p7810456/FPGADesign/Simple_MemmapPeriph/Simple_MemmapPeriph.gen/sources_1/bd/TopLevelDesign/ip/TopLevelDesign_xbar_0/TopLevelDesign_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopLevelDesign_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
