# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/base.xdc

# Block Designs: bd/TopLevelDesign/TopLevelDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TopLevelDesign || ORIG_REF_NAME==TopLevelDesign} -quiet] -quiet

# IP: bd/TopLevelDesign/ip/TopLevelDesign_processing_system7_0_0/TopLevelDesign_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TopLevelDesign_processing_system7_0_0 || ORIG_REF_NAME==TopLevelDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/TopLevelDesign/ip/TopLevelDesign_xbar_0/TopLevelDesign_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TopLevelDesign_xbar_0 || ORIG_REF_NAME==TopLevelDesign_xbar_0} -quiet] -quiet

# IP: bd/TopLevelDesign/ip/TopLevelDesign_axi_interconnect_0_0/TopLevelDesign_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TopLevelDesign_axi_interconnect_0_0 || ORIG_REF_NAME==TopLevelDesign_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/TopLevelDesign/ip/TopLevelDesign_rst_ps7_0_100M_0/TopLevelDesign_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TopLevelDesign_rst_ps7_0_100M_0 || ORIG_REF_NAME==TopLevelDesign_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/TopLevelDesign/ip/TopLevelDesign_Simple_MMap_0_0/TopLevelDesign_Simple_MMap_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TopLevelDesign_Simple_MMap_0_0 || ORIG_REF_NAME==TopLevelDesign_Simple_MMap_0_0} -quiet] -quiet

# IP: bd/TopLevelDesign/ip/TopLevelDesign_auto_pc_0/TopLevelDesign_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TopLevelDesign_auto_pc_0 || ORIG_REF_NAME==TopLevelDesign_auto_pc_0} -quiet] -quiet

# XDC: /home/p7810456/FPGADesign/Simple_MemmapPeriph/Simple_MemmapPeriph.gen/sources_1/bd/TopLevelDesign/TopLevelDesign_ooc.xdc
